os:
  - Visual Studio 2017

configuration:
  - Debug
  - Release

environment:
  CTEST_OUTPUT_ON_FAILURE: 1

install:
  - vcpkg install protobuf
  # ign-cmake
  - git clone https://github.com/ignitionrobotics/ign-cmake
  - cd ign-cmake
  - git checkout ign-cmake1
  - md build
  - cd build
  - cmake .. -DBUILD_TESTING=OFF
  - cmake --build . --target INSTALL
  # also build ign-cmake2
  - cd ..
  - md build2
  - cd build2
  - git checkout ign-cmake2
  - cmake .. -DBUILD_TESTING=OFF
  - cmake --build . --target INSTALL
  - cd ../..
  # ign-math
  - git clone https://github.com/ignitionrobotics/ign-math
  - cd ign-math
  - git checkout ign-math6
  - md build
  - cd build
  - cmake .. -DBUILD_TESTING=OFF
  - cmake --build . --target INSTALL
  - cd ../..
build_script:
  - md build
  - cd build
  - cmake ..
      -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake
      #-DCMAKE_CXX_FLAGS="-WX"
  - cmake --build . --config %CONFIGURATION%

after_build:
  - cmake --build . --config %CONFIGURATION% --target INSTALL

#test_script:
#  - cmake --build . --config %CONFIGURATION% --target RUN_TESTS
