#!/usr/bin/env python3
#
# Copyright (C) 2022 Open Source Robotics Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import argparse
import os
import subprocess
import sys

cc_header = """// Generated by gz-msgs.  DO NOT EDIT!

#include <gz/msgs/MessageFactory.hh>
#include "msgs.hh"

void RegisterAllMessages(gz::msgs::MessageFactory & factory)
"""


def main(argv=sys.argv[1:]):
    parser = argparse.ArgumentParser(
        description='Generate protobuf factory file',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument(
        '--output-cpp-path',
        help='The basepath of the generated C++ files')
    parser.add_argument(
        '--proto-path',
        required=True,
        help='The location of the protos')
    parser.add_argument(
        '--protos',
        required=True,
        help='The list of protos to include'
    )
    args = parser.parse_args(argv)

    print(args.output_cpp_path)
    print(args.proto_path)
    print(args.protos)

if __name__ == '__main__':
    sys.exit(main())
