name: Bazel CI
on:
  push:
    branches: [gz-msgs11, main]
  pull_request:
    branches: [gz-msgs11, main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: bazel-contrib/.github/.github/workflows/bazel.yaml@v7
    with:
      folders: |
        [
          ".",
        ]
      exclude: |
        [
          {"folder": ".", "bzlmodEnabled": false},
        ]
